/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/who-we-are': typeof WhoWeAreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/privacy'
    | '/products'
    | '/security'
    | '/terms'
    | '/what-we-do'
    | '/who-we-are'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/privacy'
    | '/products'
    | '/security'
    | '/terms'
    | '/what-we-do'
    | '/who-we-are'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/privacy'
    | '/products'
    | '/security'
    | '/terms'
    | '/what-we-do'
    | '/who-we-are'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  WhoWeAreRoute: WhoWeAreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
